// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Fsmxlb Rest API
//
//	Fsmxlb REST API for Baremetal Scenarios
//	Schemes:
//	  http
//	  https
//	Host: 0.0.0.0:11111
//	BasePath: /flomesh/v1
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
